# Generated by Django 4.2 on 2023-04-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_rename_summary_registerhackathon_submission_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerhackathon",
            name="submission_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registerhackathon",
            name="submission_media",
            field=models.FileField(
                blank=True, null=True, upload_to="hackathons/submissions/"
            ),
        ),
    ]
