# Generated by Django 4.2 on 2023-04-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0006_remove_registerhackathon_submission_media_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerhackathon",
            name="submission_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="hackathons/submissions/image"
            ),
        ),
    ]
