# Generated by Django 4.2 on 2023-04-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0007_alter_registerhackathon_submission_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerhackathon",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
